SPEEC-1365: upd Widget search
speechki-book/widgets pull request #35
Opened 2023-03-13 13:38 UTC by ma23-gh1

2023-03-23 13:31 UTC, sobolew commented on src/components/Widget/Widget.svelte
> +
кажется от установки `filterTags` ничего не происходит

2023-03-23 13:33 UTC, sobolew commented on src/components/SearchTags/SearchTags.svelte
> +                    {/if}
класс можно забиндить одной строкой здесь
`class="list_item {tag.selected ? 'is-selected' : ''}"`

2023-03-23 13:38 UTC, sobolew commented on src/components/Widget/Widget.svelte
> +        metaTags = filterTags.map(t => t.slug).some(t => s.meta_tags.includes(t))
можно в принципе сделать так `filterTags.some(t => s.meta_tags.includes(t.slug))`, минус перебор

2023-03-24 03:18 UTC, ma23-gh1 commented on src/components/Widget/Widget.svelte
> +
не совсем понял, по filterTags фильтруется спикер по meta_tags. Он из компонента SearchTags прилетает

2023-03-24 09:59 UTC, sobolew requested changes
<img width="327" alt="image" src="https://user-images.githubusercontent.com/21295322/227489965-f1db64a6-ff22-4b93-9a02-0cfbd57bec2b.png">

думаю нужно внешний вид привести к примерно такому же, но со шрифтом меньше

2023-04-04 09:31 UTC, merged